### PR TITLE
Layout of Add Item Page

### LINKED ISSUE #43: Layout of AddItem Page
Add Item: fix extra spacing in both mobile & desktop views
- Mobile: make tags closer so the “Add Item” button is more visible
- Desktop: remove extra spacing between items
- Both: play with spacing for the successful/unsuccessful message

## Acceptance Criteria

- [ ] Contents fit in the window height for the usability.

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description
Add Item: fix extra spacing in both mobile & desktop views
- Mobile: make tags closer so the “Add Item” button is more visible
- Desktop: remove extra spacing between items
- Both: play with spacing for the successful/unsuccessful message

## Acceptance Criteria
- [x] Contents fit in the window height for the usability. 

## Related Issue
closes #43 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Testing Steps / QA Criteria

- Please check it on your mobile to see how it looks. In the Chrome simulator, the page fits up to 666px height.
- Please check it on the browser.

### CODE REVIEW

**Comment by polly89** [comment]
This is what it looks like on my device. If you have time, maybe we could remove just a tad bit of the padding below the button so that we can see the entire screen. But it looks pretty good.
IMG_ECA6A101419C-1

**Review by polly89 — APPROVED** [review]
Left a non-blocking comment.

**Review by tialaaa — APPROVED** [review]
Looks good to me! Here's the view on my pixel 6, there's plenty of space to see everything.

Screenshot_20231006-085756

**Review by ismarjiw — APPROVED** [review]
Looks good to me! Non-blocking comment: I agree with Christina, if there's anyway the extra blank space below the `add item` button could be reduced a little, it would be perfect - Thanks! 
Screen Shot 2023-10-06 at 2 49 37 PM

**Comment by Satoshi-Sh** [comment]
Thanks for the screenshots, everyone. 
This was Iphone SE view.
Screenshot from 2023-10-06 19-27-02

If the mobile is taller, it has an extra space at the bottom. Possibly, I can fix it with flex or something but I keep it as is this time.

**Pull request merged**
