### PR TITLE
Logout Function

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description
Added a logout function to the application. For now, I just added a button with the function at the bottom of the list page. We can decide on the position later.

Would be nice to have a confirmation modal encouraging users to keep a token for future use.

## Acceptance Criteria
- When the log-out button is clicked, a user should be directed to the home page and the local storage should be cleared.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates
- Passing setListToken to the list component. 
- implement a delete function to remove "tcl-shopping-list-token" and reset setListToke to null.
- Added a log-out button to the list page.
### After
Screenshot from 2023-09-27 09-23-10

## Testing Steps / QA Criteria
When you click on the logout button 
- Redirected to the home page
- LocalStrage is cleared

### CODE REVIEW

**Review by ismarjiw — APPROVED** [review]
Looks good Satoshi!

**Review by tialaaa — COMMENTED** [review]
Thanks for doing this!

I think we would want the `Logout` button to show on the `Add Item` page too. If everyone agrees, this could become its own component that is imported into the `List` and `Add Item` views.

**Comment by polly89** [comment]
I agree with Tiala, we should have it on the `Add Item` page as well.

**Comment by Satoshi-Sh** [comment]
You can just move this button to the navbar, once you created the component.

**Comment by polly89** [comment]
> You can just move this button to the navbar, once you created the component.

Sounds good.

**Pull request closed without merging**
