### PR TITLE
replace a tag with NavLink

### LINKED ISSUE #2: 2. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouterdotcom.fly.dev/docs/en/v6/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

### PR DESCRIPTION
**Pull request by ismarjiw**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

- In this PR, replaced all instances of `a tags` with `NavLink` components. This change ensures that when a user clicks on a link, the app now correctly routes them to the intended route while also applying appropriate styling for active links.

## Related Issue

Closes #2

## Acceptance Criteria

The links all function as expected using the NavLink component from react-router-dom

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

before

### After

after

## Testing Steps / QA Criteria

- Conducted thorough testing by clicking on various links (`Home`, `List`, `Add Item`) within the app to ensure proper navigation and highlighting of active links.

### CODE REVIEW

**Comment by polly89** [comment]
Looks great!

**Review by tialaaa — APPROVED** [review]
Nice work! The code is clean and makes sense. All links worked for me when testing via the preview URL.

**Review by polly89 — APPROVED** [review]
Great job! The code looks clean and the links work.

**Review by 01001101CK — APPROVED** [review]
Great job using react-router, Ismarji, and Satoshi!! For practice, try to include more of the impact of your code on the PR. For example, navigate among "Home", "List", and "Add item" pages. Your colleagues might not know React that well. :)

**Pull request merged**
