### PR TITLE
Tailwind Setup

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

- Followed setup Install [Tailwind CSS with Vite](https://tailwindcss.com/docs/guides/vite)
- Added our project's main color to tailwind.config.js
- Added styling to h1 h2 as an example. Feel free to change this. 

## Acceptance Criteria
- Check if TailwindCss works on your end.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates
Screenshot from 2023-09-29 10-28-51

## Testing Steps / QA Criteria
- After `npm install` and `npm start`, you can check if the smart shopping List on the Homepage is green or not.

### CODE REVIEW

**Review by ismarjiw — APPROVED** [review]
Looks good Satoshi!

**Comment by polly89** [comment]
I was going to add the [classnames](https://www.npmjs.com/package/classnames) library as well. Do you want to add it to this PR or should I create a new one?

The library basically gives you a function called `classNames`, which takes in a bunch of strings (tailwind properties in this case) and returns a single string that's appropriate to use as a className prop.

**Review by polly89 — APPROVED** [review]
I'm approving the PR as is. Let me know if you decide to add the classnames library here or if I should create a separate PR.

**Comment by Satoshi-Sh** [comment]
It should work fine since two people have checked already. I merge this pull request.

**Pull request merged**
